services:
  donetick:
    image: donetick/donetick:latest
    container_name: donetick
    restart: always
    ports:
      - 8085:4555
    volumes:
      - ./data:/donetick-data
      - ./config:/config
    environment:
      - DT_ENV=selfhosted
      - DT_SQLITE_PATH=/donetick-data/donetick.db
      
